GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Kesämuistoja",
    "author": "Kesä Esa",
    "url": "https://www.google.com/search?q=summer",
    "likes": 8,
    "userId": "5f1ff41570350c0bc0f0c3e0"
}

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "jotain myyta",
    "author": "talvea",
    "url": "https://www.google.com/search?q=winter",
    "likes": 8,
    "userId": "5f1ff6f611257b37e4395157"
}

###

DELETE http://localhost:3003/api/blogs/5f213a9e0e45f641ac6bf45f
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1aGF4aXMiLCJpZCI6IjVmMjEyOTlkOGI1ZmI5MzUzMDRhZmRhYSIsImlhdCI6MTU5NjAxMjc0Nn0.i9LMEKxoRp7mzcs3KKWqkvfDJ1YDBhEFEWoO07splKc



###

POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "juhaxis",
    "name": "Juan Lelo",
    "password": "salaisuus"
}

###

POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "juhaxis",
    "password": "salaisuus"
}

###

POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1aGF4aXMiLCJpZCI6IjVmMjE2MzU5NThlMDgwMzkyNDA0OWJjMiIsImlhdCI6MTU5NjAyMzY0OH0.fh3UWFRC2FPTDwcTW4UH3vAmUUodpU__hXHTHRcJbJE

{
    "title": "jotain mystuta",
    "author": "talvea",
    "url": "https://www.google.com/search?q=winter",
    "likes": 78,
    "userId": "5f21635958e0803924049bc2"
}

###

POST http://localhost:3003/api/api/testing